# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [78]:
import numpy as np
import pandas as pd

In [79]:
customer_data_insurance_df = pd.read_csv("Customer_data.csv")
customer_data_insurance2_df = pd.read_csv("Customer_data2.csv")
customer_data_insurance3_df = pd.read_csv("Customer_data3.csv")

In [80]:
customer_data_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 417.4 KB

In [81]:
customer_data_insurance_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [82]:
customer_data_insurance2_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.2,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.2,Corporate Auto,Two-Door Car

In [83]:
customer_data_insurance3_df.head()

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [84]:
all_customer_data_df = pd.concat([customer_data_insurance_df, customer_data_insurance2_df, customer_data_insurance3_df], axis=0, ignore_index=True)

In [85]:
all_customer_data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   9137 non-null   str
 1   ST                         2067 non-null   str
 2   GENDER                     1945 non-null   str
 3   Education                  9137 non-null   str
 4   Customer Lifetime Value    9130 non-null   object
 5   Income                     9137 non-null   float64
 6   Monthly Premium Auto       9137 non-null   float64
 7   Number of Open Complaints  9137 non-null   object
 8   Policy Type                9137 non-null   str
 9   Vehicle Class              9137 non-null   str
 10  Total Claim Amount         9137 non-null   float64
 11  State                      7070 non-null   str
 12  Gender                     7070 non-null   str
dtypes: float64(3), object(2), str(8)
memory usage: 1.6+ MB

In [86]:
all_customer_data_df["state"] = all_customer_data_df["ST"].fillna(all_customer_data_df["State"])

In [87]:
all_customer_data_df = all_customer_data_df.drop(["ST", "State"], axis=1)

In [88]:
all_customer_data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   9137 non-null   str
 1   GENDER                     1945 non-null   str
 2   Education                  9137 non-null   str
 3   Customer Lifetime Value    9130 non-null   object
 4   Income                     9137 non-null   float64
 5   Monthly Premium Auto       9137 non-null   float64
 6   Number of Open Complaints  9137 non-null   object
 7   Policy Type                9137 non-null   str
 8   Vehicle Class              9137 non-null   str
 9   Total Claim Amount         9137 non-null   float64
 10  Gender                     7070 non-null   str
 11  state                      9137 non-null   str
dtypes: float64(3), object(2), str(7)
memory usage: 1.5+ MB

In [89]:
all_customer_data_df["gender"] = all_customer_data_df["GENDER"].fillna(all_customer_data_df["Gender"])
all_customer_data_df = all_customer_data_df.drop(["GENDER", "Gender"], axis=1)

In [90]:
all_customer_data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   9137 non-null   str
 1   Education                  9137 non-null   str
 2   Customer Lifetime Value    9130 non-null   object
 3   Income                     9137 non-null   float64
 4   Monthly Premium Auto       9137 non-null   float64
 5   Number of Open Complaints  9137 non-null   object
 6   Policy Type                9137 non-null   str
 7   Vehicle Class              9137 non-null   str
 8   Total Claim Amount         9137 non-null   float64
 9   state                      9137 non-null   str
 10  gender                     9015 non-null   str
dtypes: float64(3), object(2), str(6)
memory usage: 1.5+ MB

In [91]:
def cle_for(df, state_conversion, gender_conversion):
    # Cleaning columns
    df.columns = df.columns.str.lower().str.replace(' ', '_')

    # Drop rows where all elements are NaN
    df = df.dropna(axis=0, how="all")
    
    # Map and replace categories
    df["state"] = df["state"].map(state_conversion).fillna(df["state"])
    df["gender"] = df["gender"].map(gender_conversion).fillna(df["gender"])
    return df

In [92]:
state_conversion = {
    'Cali': 'California', 'AZ': 'Arizona', 'WA': 'Washington',
    'Washington': 'Washington', 'Arizona': 'Arizona', 'Nevada': 'Nevada', 'California': 'California', 'Oregon': 'Oregon'
}

In [93]:
gender_conversion = {
    "Male": "M", "Female": "F", "Femal": "F", "female": "F"
}

In [94]:
cleaned_customer_data_insurance_df = cle_for(all_customer_data_df, state_conversion, gender_conversion)
cleaned_customer_data_insurance_df = cleaned_customer_data_insurance_df.reset_index(drop=True)

In [95]:
cleaned_customer_data_insurance_df.columns

Index(['customer', 'education', 'customer_lifetime_value', 'income',
       'monthly_premium_auto', 'number_of_open_complaints', 'policy_type',
       'vehicle_class', 'total_claim_amount', 'state', 'gender'],
      dtype='str')

In [96]:
cleaned_customer_data_insurance_df["education"].unique()

<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Bachelors',
 'Doctor']
Length: 6, dtype: str

In [97]:
cleaned_customer_data_insurance_df["education"] = cleaned_customer_data_insurance_df["education"].replace({
    "Bachelors": "Bachelor"
})

In [98]:
cleaned_customer_data_insurance_df["education"].unique()

<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor']
Length: 5, dtype: str

In [99]:
cleaned_customer_data_insurance_df["customer_lifetime_value"].unique()

array([nan, '697953.59%', '1288743.17%', ..., 8163.890428, 7524.442436,
       2611.836866], shape=(8212,), dtype=object)

In [100]:
cleaned_customer_data_insurance_df["customer_lifetime_value"] = cleaned_customer_data_insurance_df["customer_lifetime_value"].str.replace('%', '', regex=False)
cleaned_customer_data_insurance_df["customer_lifetime_value"] = pd.to_numeric(
    cleaned_customer_data_insurance_df["customer_lifetime_value"], errors='coerce'
    )
median_value = cleaned_customer_data_insurance_df["customer_lifetime_value"].median()
cleaned_customer_data_insurance_df["customer_lifetime_value"] = cleaned_customer_data_insurance_df["customer_lifetime_value"].fillna(median_value)

In [101]:
cleaned_customer_data_insurance_df["customer_lifetime_value"].unique()

array([ 572027.54,  697953.59, 1288743.17, ...,  568964.41,  368672.38,
        399258.39], shape=(1924,))

In [102]:
cleaned_customer_data_insurance_df["number_of_open_complaints"].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', 0, 2,
       3, 1, 5, 4], dtype=object)

In [103]:
cleaned_customer_data_insurance_df["number_of_open_complaints"].dtypes

dtype('O')

In [104]:
cleaned_customer_data_insurance_df["number_of_open_complaints"] = cleaned_customer_data_insurance_df["number_of_open_complaints"].astype(str)

In [105]:
cleaned_customer_data_insurance_df["number_of_open_complaints"].dtypes

In [106]:
def convert_values(x):
    if pd.isnull(x):
        return pd.NA  # Handle missing values
    if isinstance(x, str) and "/" in x:
        return int(x.split("/")[1])  # Extract the second part of the split string
    try:
        return int(x)  # Directly convert numeric strings or numbers
    except ValueError:
        return pd.NA  # In case of any unexpected values

cleaned_customer_data_insurance_df["number_of_open_complaints"] = (
    cleaned_customer_data_insurance_df["number_of_open_complaints"]
    .apply(convert_values)
    .astype(pd.Int64Dtype())
)

In [107]:
cleaned_customer_data_insurance_df["number_of_open_complaints"].unique()

<IntegerArray>
[0, 2, 1, 3, 5, 4]
Length: 6, dtype: Int64

In [108]:
cleaned_customer_data_insurance_df.columns

Index(['customer', 'education', 'customer_lifetime_value', 'income',
       'monthly_premium_auto', 'number_of_open_complaints', 'policy_type',
       'vehicle_class', 'total_claim_amount', 'state', 'gender'],
      dtype='str')

In [109]:
cleaned_customer_data_insurance_df["policy_type"].unique()

<ArrowStringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto']
Length: 3, dtype: str

In [110]:
cleaned_customer_data_insurance_df["vehicle_class"].unique()

<ArrowStringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car']
Length: 6, dtype: str

In [111]:
cleaned_customer_data_insurance_df["vehicle_class"] = cleaned_customer_data_insurance_df["vehicle_class"].replace(
    {"Sports Car": "Luxury", "Luxury SUV": "Luxury", "Luxury Car": "Luxury"}
)
cleaned_customer_data_insurance_df["vehicle_class"].unique()

<ArrowStringArray>
['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury']
Length: 4, dtype: str

In [112]:
cleaned_customer_data_insurance_df["gender"].unique()

<ArrowStringArray>
[nan, 'F', 'M']
Length: 3, dtype: str

In [120]:
cleaned_customer_data_insurance_df["state"].unique()

<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon']
Length: 5, dtype: str

In [115]:
cleaned_customer_data_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   str
 1   education                  9137 non-null   str
 2   customer_lifetime_value    9137 non-null   float64
 3   income                     9137 non-null   float64
 4   monthly_premium_auto       9137 non-null   float64
 5   number_of_open_complaints  9137 non-null   Int64
 6   policy_type                9137 non-null   str
 7   vehicle_class              9137 non-null   str
 8   total_claim_amount         9137 non-null   float64
 9   state                      9137 non-null   str
 10  gender                     9015 non-null   str
dtypes: Int64(1), float64(4), str(6)
memory usage: 1.2 MB

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [117]:
marketing_customer_analysis_df = pd.read_csv("marketing_customer_analysis_clean.csv")

In [119]:
marketing_customer_analysis_df.nunique()

unnamed:_0                       10910
customer                          9134
state                                5
customer_lifetime_value           8041
response                             2
coverage                             3
education                            5
effective_to_date                   59
employmentstatus                     5
gender                               2
income                            5694
location_code                        3
marital_status                       3
monthly_premium_auto               202
months_since_last_claim             37
months_since_policy_inception      100
number_of_open_complaints            7
number_of_policies                   9
policy_type                          3
policy                               9
renew_offer_type                     4
sales_channel                        4
total_claim_amount                5106
vehicle_class                        6
vehicle_size                         3
vehicle_type                         1
month                                2
dtype: int64

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [124]:
premium_pivot_table = marketing_customer_analysis_df.pivot_table(
    values='monthly_premium_auto',
    index='sales_channel',
    aggfunc='sum'
)

premium_pivot_table = premium_pivot_table.round(2)

print(premium_pivot_table)

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

In [125]:
#The data might hint at market preferences that skew toward personal interaction.
# This could be critical information when planning marketing campaigns or customer interaction strategies.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [123]:
pivot_table_clv = marketing_customer_analysis_df.pivot_table(
    values='customer_lifetime_value',
    index='gender',
    columns='education',
    aggfunc='mean'
)

pivot_table_clv = pivot_table_clv.round(2)

print(pivot_table_clv)

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

In [126]:
#Given the higher CLVs among females with "High School or Below" and males with "Masters," these groups could be prime targets for retention strategies and upselling higher insurance packages or additional service offerings.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [128]:
df_complaints = marketing_customer_analysis_df.groupby(['policy_type', 'month']).size().reset_index(name='number_of_complaints')

print(df_complaints)

      policy_type  month  number_of_complaints
0  Corporate Auto      1                  1252
1  Corporate Auto      2                  1089
2   Personal Auto      1                  4329
3   Personal Auto      2                  3799
4    Special Auto      1                   237
5    Special Auto      2                   204